import "../styles/globals.css"
import Navbar from "../components/navbar"
import Footer from "../components/footer"
import { inter } from "../styles/fonts"

// if (typeof window !== "undefined") {
//   require("pace-progressbar")
//   require("pace-progressbar/themes/blue/pace-theme-minimal.css")
// }

export const metadata = {
  title: "Andel Husbands | Freelance Web and App Developer",
  description: "Generated by Next.js",
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en" className={`${inter.variable}`}>
      <body>
        <Navbar />
        <main className="mx-auto max-w-[1100px] px-[5%] pb-[5%] pt-[100px] text-white lg:px-0">
          {children}
        </main>
        <Footer />
      </body>
      {/* {!noFooter && <Footer />} */}
    </html>
  )
}
